export interface StaticPoem {
  id: string;
  title: string;
  author: string;
  language: string;
  country: string;
  persianTranslation: string;
  originalText: string;
  licenseType: string;
  legalityScore: string;
  qualityScore: number;
  sourceUrl: string;
  sourceName: string;
}

export const STATIC_POEMS: StaticPoem[] = [
  {
    id: "static-1",
    title: "The Road Not Taken",
    author: "Robert Frost",
    language: "en",
    country: "US",
    persianTranslation: "در جنگلی زرد، دو راه از هم جدا شد\nو من اندوهگین که نمی‌توانستم هر دو را بپویم",
    originalText: "Two roads diverged in a yellow wood,\nAnd sorry I could not travel both",
    licenseType: "PUBLIC_DOMAIN",
    legalityScore: "SAFE",
    qualityScore: 0.92,
    sourceUrl: "https://gutenberg.org",
    sourceName: "Project Gutenberg",
  },
  {
    id: "static-2",
    title: "Hope is the thing with feathers",
    author: "Emily Dickinson",
    language: "en",
    country: "US",
    persianTranslation: "امید آن چیز پربال است\nکه در جان می‌نشیند",
    originalText: "Hope is the thing with feathers\nThat perches in the soul",
    licenseType: "PUBLIC_DOMAIN",
    legalityScore: "SAFE",
    qualityScore: 0.88,
    sourceUrl: "https://gutenberg.org",
    sourceName: "Project Gutenberg",
  },
  {
    id: "static-3",
    title: "Old Pond",
    author: "Matsuo Bashō",
    language: "ja",
    country: "JP",
    persianTranslation: "برکه‌ی کهنه\nقورباغه‌ای در جهید\nصدای آب.",
    originalText: "古池や\n蛙飛び込む\n水の音",
    licenseType: "PUBLIC_DOMAIN",
    legalityScore: "SAFE",
    qualityScore: 0.85,
    sourceUrl: "https://wikisource.org",
    sourceName: "Wikisource",
  },
  {
    id: "static-4",
    title: "Quiet Night Thought",
    author: "Li Bai",
    language: "zh",
    country: "CN",
    persianTranslation: "پیشِ بستر، نورِ ماهِ روشن\nگمان برف‌وزر بر زمین است",
    originalText: "床前明月光\n疑是地上霜",
    licenseType: "PUBLIC_DOMAIN",
    legalityScore: "SAFE",
    qualityScore: 0.86,
    sourceUrl: "https://wikisource.org",
    sourceName: "Wikisource",
  },
  {
    id: "static-5",
    title: "Fire and Ice",
    author: "Robert Frost",
    language: "en",
    country: "US",
    persianTranslation: "بعضی می‌گویند جهان در آتش فرو خواهد رفت،\nبعضی در یخ.",
    originalText: "Some say the world will end in fire,\nSome say in ice.",
    licenseType: "PUBLIC_DOMAIN",
    legalityScore: "SAFE",
    qualityScore: 0.91,
    sourceUrl: "https://gutenberg.org",
    sourceName: "Project Gutenberg",
  },
  {
    id: "static-6",
    title: "Demain dès l'aube",
    author: "Victor Hugo",
    language: "fr",
    country: "FR",
    persianTranslation: "فردا، به سپیده‌دم، در ساعتی که دشت سفید می‌شود،\nمی‌روم.",
    originalText: "Demain, dès l'aube, à l'heure où blanchit la campagne,\nJe partirai.",
    licenseType: "PUBLIC_DOMAIN",
    legalityScore: "SAFE",
    qualityScore: 0.90,
    sourceUrl: "https://gutenberg.org",
    sourceName: "Project Gutenberg",
  },
  {
    id: "static-7",
    title: "Der Panther",
    author: "Rainer Maria Rilke",
    language: "de",
    country: "DE",
    persianTranslation: "نگاهش از رفت‌و‌آمدِ میله‌ها\nچنان خسته شده که چیزی نگه نمی‌دارد.",
    originalText: "Sein Blick ist vom Vorübergehn der Stäbe\nso müd geworden.",
    licenseType: "PUBLIC_DOMAIN",
    legalityScore: "SAFE",
    qualityScore: 0.89,
    sourceUrl: "https://gutenberg.org",
    sourceName: "Project Gutenberg",
  },
  {
    id: "static-8",
    title: "Noche de verano",
    author: "Antonio Machado",
    language: "es",
    country: "ES",
    persianTranslation: "شبی است از تابستان.\nهوا بوی شکوفه می‌دهد.",
    originalText: "Es una noche de verano.\nEl aire huele a azahar y a mujer.",
    licenseType: "PUBLIC_DOMAIN",
    legalityScore: "SAFE",
    qualityScore: 0.87,
    sourceUrl: "https://wikisource.org",
    sourceName: "Wikisource",
  },
  {
    id: "static-9",
    title: "Я вас любил",
    author: "Alexander Pushkin",
    language: "ru",
    country: "RU",
    persianTranslation: "دوستتان داشتم: عشق، شاید،\nدر جانم هنوز کاملاً نبوده است.",
    originalText: "Я вас любил: любовь еще, быть может,\nВ душе моей угасла не совсем.",
    licenseType: "PUBLIC_DOMAIN",
    legalityScore: "SAFE",
    qualityScore: 0.91,
    sourceUrl: "https://wikisource.org",
    sourceName: "Wikisource",
  },
  {
    id: "static-10",
    title: "از غزل‌های شمس",
    author: "Jalaluddin Rumi",
    language: "fa",
    country: "IR",
    persianTranslation: "بشنو این نی چون شکایت می‌کند\nاز جدایی‌ها حکایت می‌کند",
    originalText: "بشنو این نی چون شکایت می‌کند\nاز جدایی‌ها حکایت می‌کند",
    licenseType: "PUBLIC_DOMAIN",
    legalityScore: "SAFE",
    qualityScore: 0.95,
    sourceUrl: "https://ganjoor.net",
    sourceName: "Ganjoor",
  },
];
